version: '3'

services:
  postgres:
        restart: unless-stopped
        image: postgres:15
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        networks:
          - todo_network

  django:
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        volumes:
          - static_volume:/app/static
          - media_volume:/app/media
        networks:
          - todo_network
        depends_on:
          - postgres

  nginx:
        restart: unless-stopped
        build:
          context: nginx/
          dockerfile: Dockerfile
        ports:
          - "80:80"
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d/default.conf
          - static_volume:/app/static
          - media_volume:/app/media
        networks:
          - todo_network
        depends_on:
          - django

volumes:
    static_volume:
    media_volume:
    postgres_data:
networks:
  todo_network:
    driver: bridge